### ISSUE TITLE
module 'pdfminer.pdfparser' has no attribute 'PDFDocument'

### ISSUE THREAD

**Issue by paulperry** [felipeochoa/minecart#20] opened 2018-10-29 19:00 UTC
```
AttributeError                            Traceback (most recent call last)
<ipython-input-56-bbdbee9a5a97> in <module>()
----> 1 doc = minecart.Document(fp)
      2 page = doc.get_page(1)
      3 for shape in page.shapes.iter_in_bbox((0, 0, 100, 200)):
      4     print(shape.path, shape.fill.color.as_rgb())
      5 im = page.images[0].as_pil()  # requires pillow

~/anaconda3/lib/python3.6/site-packages/minecart/miner.py in __init__(self, pdffile)
    328         self.interpreter = ColoredInterpreter(res_mgr, self.device)
    329         self.parser = pdfminer.pdfparser.PDFParser(pdffile)
--> 330         self.doc = pdfminer.pdfparser.PDFDocument(caching=True)
    331         self.parser.set_document(self.doc)
    332         self.doc.set_parser(self.parser)

AttributeError: module 'pdfminer.pdfparser' has no attribute 'PDFDocument'
```

pdfminer verison '20170419' has moved PDFDocument  to pdfminer.pdfdocument .  FYI

**Comment by felipeochoa** [comment] 2018-11-13 19:05
Looks like a duplicate of #13

**Closed as completed by felipeochoa** 2018-11-13 19:05 UTC
