### ISSUE TITLE
 import minecart  pdffile = open('C:/Users/intkonsys/.spyder-py3/pp1.pdf', 'rb') doc = minecart.Document(pdffile)  page = doc.get_page(0) # getting a single page  #iterating through all pages for page in doc.iter_pages():     im = page.images[0].as_pil()  # requires pillow     print(im)

### ISSUE THREAD

**Issue by Ashu-jun** [felipeochoa/minecart#24] opened 2019-03-11 11:42 UTC
Hi I am New to python. I am trying to extract image from pdf file using above code. 
I have install pdfminer.six, minecart.
I am using Python 3.7. 
This is the error i am getting please help me 

  class ColoredState(pdfminer.pdfinterp.PDFGraphicState):

AttributeError: module 'pdfminer' has no attribute 'pdfinterp'

import minecart

pdffile = open('C:/Users/intkonsys/.spyder-py3/pp1.pdf', 'rb')
doc = minecart.Document(pdffile)

page = doc.get_page(0) # getting a single page

#iterating through all pages
for page in doc.iter_pages():
    im = page.images[0].as_pil()  # requires pillow
    print(im)

**Comment by felipeochoa** [comment] 2019-03-11 14:09
Looks like you are using the wrong pdfminer package. There are multiple duplicate of this issue which you should check out

**Closed as completed by felipeochoa** 2019-03-11 14:09 UTC

**Comment by Ashu-jun** [comment] 2019-03-12 04:52
ok thank u
